node default {
  include "001_create_file"
  include "002_create_folder"
  include "003_config_file"
  include "004_create_folder_structure"
  include "005_create_link"
  # include "006_ntpdate_package"
  # include "007_ntpdate_uninstall"
  # include "008_ntpdate_from_source"
  include "010_notify_fqdn"
  # include "011_user_admin"
  # include "012_remove_admin"
  # include "013_user_password"
  include "014_encrypted_password"
  # include "015_create_group"
  include "016_remove_group"
  include "017_sshauth"
  # include "018_sshkey"
  include "019_sshkey_remove"
  include "020_hosts"
}
